version: 2.1

jobs:
  build-learning-csharp:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Run
          command: dotnet run --project src/learning-csharp

  test-learning-csharp:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Test
          command: >
            dotnet test --no-build --logger trx 
            /p:CollectCoverage=true
            /p:CoverletOutputFormat=lcov
            /p:CoverletOutput=TestResults/lcov.info
            /p:Exclude="[xunit.*]*"
            /p:ThresholdType=line
            /p:ThresholdStat=total
            /p:Threshold=80
            src/learning-csharp-test
      - run:
          name: Codecov
          command: |
            dotnet tool install -g Codecov.Tool
            export PATH="$PATH:/root/.dotnet/tools"
            codecov -f "src/learning-csharp-test/TestResults/lcov.info" --token 41a05995-8614-4109-b50d-12b2c97f8c4d

workflows:
  version: 2
  learning-csharp:
    jobs:
      - build-learning-csharp
      - test-learning-csharp:
          requires:
            - build-learning-csharp
