version: "3.7"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    environment:
      - SA_PASSWORD=Pass@w0rd
      - ACCEPT_EULA=Y
    ports:
      - "6433:1433"
